# Generated by Django 5.2.8 on 2025-11-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0003_reporter_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
